import { MemberInvoice } from '../types';
import { calculateEndDate, getTodayDateString } from './dateUtils';

export function getInitialSampleInvoices(): MemberInvoice[] {
  const today = getTodayDateString();

  return [
    {
      id: 'inv-1001',
      receiptNumber: 'TBT-2026-1038',
      receiptDate: today,
      paymentMethod: 'UPI',
      paymentReference: 'UPI/AXIS/9871239812',
      customerName: 'Aman Sharma',
      customerPhone: '+91 98112 34567',
      customerAddress: 'House 204, Sector 15-A, Chandigarh',
      customerEmail: 'aman.sharma@example.com',
      planName: 'Annual VIP Membership',
      description: '12 Months Gym & Spa All-Access VIP Membership Fee',
      startDate: today,
      durationMonths: 12,
      endDate: calculateEndDate(today, 12),
      basePrice: 15000,
      taxRate: 18,
      taxAmount: 2700,
      cgstAmount: 1350,
      sgstAmount: 1350,
      totalAmount: 17700,
      isTaxEnabled: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'inv-1002',
      receiptNumber: 'TBT-2026-1039',
      receiptDate: calculateEndDate(today, -2), // 2 months ago
      paymentMethod: 'Card',
      paymentReference: 'HDFC-POS-8921',
      customerName: 'Priya Mehra',
      customerPhone: '+91 99201 44556',
      customerAddress: 'SCO 12, Sector 35-C, Chandigarh',
      customerEmail: 'priya.mehra@example.com',
      planName: 'Cardio & Strength Training',
      description: '3 Months Cardio & Strength Training Membership Fee',
      startDate: calculateEndDate(today, -2),
      durationMonths: 3,
      endDate: calculateEndDate(calculateEndDate(today, -2), 3), // expires in 1 month
      basePrice: 4500,
      taxRate: 18,
      taxAmount: 810,
      cgstAmount: 405,
      sgstAmount: 405,
      totalAmount: 5310,
      isTaxEnabled: true,
      createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'inv-1003',
      receiptNumber: 'TBT-2026-1040',
      receiptDate: calculateEndDate(today, -1),
      paymentMethod: 'Cash',
      customerName: 'Rahul Verma',
      customerPhone: '+91 97188 90123',
      customerAddress: 'House 1022, Sector 22-B, Chandigarh',
      customerEmail: 'rahul.verma@example.com',
      planName: 'Standard Gym Membership',
      description: '1 Month Standard Gym Fitness Fee',
      startDate: calculateEndDate(today, -1),
      durationMonths: 1,
      // Expires around today / within 3 days
      endDate: calculateEndDate(calculateEndDate(today, -1), 1),
      basePrice: 1800,
      taxRate: 18,
      taxAmount: 324,
      cgstAmount: 162,
      sgstAmount: 162,
      totalAmount: 2124,
      isTaxEnabled: true,
      createdAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'inv-1004',
      receiptNumber: 'TBT-2026-1041',
      receiptDate: '2026-05-10',
      paymentMethod: 'Net Banking',
      paymentReference: 'NEFT-ICICI-88129',
      customerName: 'Siddharth Roy',
      customerPhone: '+91 98450 11223',
      customerAddress: 'Flat 401, DLF Valley, Panchkula, Chandigarh',
      customerEmail: 'sroy@example.com',
      planName: 'Personal Training (PT) Package',
      description: '3 Months Personal Training (1-on-1) Fitness Package',
      startDate: '2026-05-10',
      durationMonths: 3,
      endDate: '2026-08-10', // Expired
      basePrice: 9000,
      taxRate: 18,
      taxAmount: 1620,
      cgstAmount: 810,
      sgstAmount: 810,
      totalAmount: 10620,
      isTaxEnabled: true,
      createdAt: new Date('2026-05-10T10:00:00Z').toISOString(),
    }
  ];
}
